# LAB 1(02/08/2018): Split the dataset into train and test.

In [7]:
import numpy as np

In [8]:
train = []
#test1=[]
a=[]

In [9]:
data = np.random.randint(low=1,high=100,size=(100,5))
#print(data)

ind=np.random.randint(low=0,high=99,size=100)
#print(ind)

In [10]:
for i in range(70):
    rain.append(data[i])
    #train.append(data[ind[i]])
    a.append(i)

In [13]:
train=np.array(train)
test=np.delete(data,a,axis=0)
print(type(train))
print(type(test))
print("Train set: size=",len(train))
print(train)
print('\n')
print("Test set: size=",len(test))
print(test)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Train set: size= 70
[[71 25 48 23 98]
 [83 45 59 71 60]
 [96 96 31 46 11]
 [49 48 97 78 70]
 [68 49 75 50 30]
 [ 1 30 42  8 19]
 [51 66 63 64 38]
 [47 77 66 23 42]
 [ 4 13 89 50  5]
 [47 25 93 50 69]
 [14 42 22 62  4]
 [55 34 45 67 73]
 [95 23 64 68 22]
 [ 4 92 83 25 63]
 [35 74 60 47 85]
 [76 22 30 51 79]
 [45 95 76 44 84]
 [81 27 58 76 50]
 [76 27 74 97 77]
 [40 52 21 92 41]
 [82 54 88 48 77]
 [92 33 76 51 63]
 [13 28 94 96 65]
 [24 39 32 22 86]
 [43 31 98 48 60]
 [18  2 91 44 24]
 [56 66 25 34 83]
 [ 5  8 71 92 34]
 [92 87 61 88 45]
 [77  1 97 31 71]
 [80 12 77 53 81]
 [18 73 12 51 35]
 [87 78 68 27 58]
 [87 93 83 13 15]
 [32 57 23 97 71]
 [31 66 55 60 84]
 [49 25 13 78 70]
 [34  8 32 47 68]
 [56 67 98 61 13]
 [16 29 56 53 28]
 [54 72 12 38 58]
 [95 75 41 76 13]
 [ 7  2 44 42 52]
 [82 48 93 61 99]
 [77 15 24 20 96]
 [62 24 87 58 19]
 [44 93 65 12 42]
 [38 89 83 42 88]
 [77  8 63 40 20]
 [54 80 52 86 20]
 [19 16 36 90 28]
 [17 35 77 66 